set.seed(234)
df <- read.csv("project1.csv")
df2 <- df
df3 <- df2[df2$horsepower != "?",]
df3$horsepower <- as.numeric(df3$horsepower)
df3 <- df3[,- c(7,8,9)]
samp <- sample(1:398, 300)
train <- df3[samp, ]
test <- df3[-samp, ]
rownames(test) <- seq(length = nrow(test))
train[!complete.cases(train),]
train <- train[complete.cases(train),]
######## Models ###########
model <- lm(mpg ~ ., data = train)
summary(model)
model2 <- lm(mpg ~ cylinder , data = train)
summary(model2)
model3 <- lm(mpg ~ displacement, data = train)
summary(model3)
model4 <- lm(mpg ~ horsepower, data = train)
summary(model4)
model5 <- lm(mpg ~ weight, data = train)
summary(model5)
model6 <- lm(mpg ~ acceleration, train)
summary(model6)
model7 <- lm(mpg ~ cylinder + displacement , data = train)
summary(model7)
model8 <- lm(mpg ~ cylinder + horsepower , data = train)
summary(model8)
model9 <- lm(mpg ~ cylinder + weight, data = train)
summary(model9)
model10 <- lm(mpg ~ cylinder + acceleration , data = train)
summary(model10)
model11 <- lm(mpg ~ cylinder + displacement + horsepower , data = train)
summary(model11)
model12 <- lm(mpg ~ cylinder + displacement + weight, data = train)
summary(model12)
model13 <- lm(mpg ~ cylinder + displacement + acceleration, data = train)
summary(model13)
model14 <- lm(mpg ~ cylinder + displacement + horsepower + weight , data = train)
summary(model14)
model15 <- lm(mpg ~ cylinder + displacement + horsepower + acceleration, data = train)
summary(model15)
model16 <- lm(mpg ~ cylinder + horsepower + weight + acceleration  , data = train)
summary(model16)
model17 <- lm(mpg ~ cylinder + horsepower + weight  , data = train)
summary(model17)
model18 <- lm(mpg ~ cylinder + weight + acceleration, data = train)
summary(model18)
model19 <- lm(mpg ~ displacement + horsepower, data = train)
summary(model19)
model20 <- lm(mpg ~ displacement + weight , data = train)
summary(model20)
model21 <- lm(mpg ~ displacement + acceleration, data = train)
summary(model21)
model22 <- lm(mpg ~ displacement + horsepower  + weight, data = train)
summary(model22)
model23 <- lm(mpg ~ displacement + horsepower + acceleration, data = train)
summary(model23)
model24 <- lm(mpg ~ displacement + horsepower  + weight + acceleration, data = train)
summary(model24)
model25 <- lm(mpg ~ displacement + weight + acceleration, data = train)
summary(model25)
model26 <- lm(mpg ~ horsepower + weight, data = train)
summary(model26)
model27 <- lm(mpg ~ horsepower + acceleration, data = train)
summary(model27)
model28 <- lm(mpg ~ horsepower + weight + acceleration, data = train)
summary(model28)
model29 <- lm(mpg ~ weight + acceleration, data = train)
summary(model29)
#####################################
#### Model 1
model_pred <- predict(model, test, type = "response")
test_cars <- test[,1]
error_model <- test_cars - model_pred 
plot(error_model, xlab = "Error", ylab = "Residual", main = "Model 1")
abline(0,0)
summary(error_model)
hist(error_model, prob = T, breaks = 10, xlab = "Error Residual", ylab = "Denisty", main = "Model 1")
lines(density(error_model), col = "red")
mu_e <- mean(error_model)
v_e <- var(error_model)
sd_e <- sqrt(v_e)
x_e <- seq(-11, 16, length = 20)
y_e <- dnorm(x_e, mu_e, sd_e)
lines(x_e, y_e, col = "blue")
##############################################
#### Model 20
model_pred20 <- predict(model20, test, type = "response")
test_cars <- test[,1]
error_model20 <- test_cars - model_pred20
plot(error_model20, xlab = "Error", ylab = "Residual", main = "Model 20")
abline(0,0)
summary(error_model20)
hist(error_model20, prob = T, breaks = 10, xlab = "Error Residual", ylab = "Denisty", main = "Model 20")
lines(density(error_model20), col = "red")
mu_e <- mean(error_model20)
v_e <- var(error_model20)
sd_e <- sqrt(v_e)
x_e <- seq(-10, 16, length = 20)
y_e <- dnorm(x_e, mu_e, sd_e)
lines(x_e, y_e, col = "blue")
##############################################
### Model 14
model_pred14 <- predict(model14, test, type = "response")
test_cars <- test[,1]
error_model14 <- test_cars - model_pred14 
plot(error_model14, xlab = "Error", ylab = "Residual", main = "Model 14")
abline(0,0)
summary(error_model14)
hist(error_model14, prob = T, breaks = 10, xlab = "Error Residual", ylab = "Denisty", main = "Model 14")
lines(density(error_model14), col = "red")
mu_e <- mean(error_model14)
v_e <- var(error_model14)
sd_e <- sqrt(v_e)
x_e <- seq(-10, 16, length = 20)
y_e <- dnorm(x_e, mu_e, sd_e)
lines(x_e, y_e, col = "blue")
##############################################
######### Model 22
model_pred22 <- predict(model22, test, type = "response")
test_cars <- test[,1]
error_model22 <- test_cars - model_pred22
plot(error_model22, xlab = "Error", ylab = "Residual", main = "Model 22")
abline(0,0)
summary(error_model22)
hist(error_model22, prob = T, breaks = 10, xlab = "Error Residual", ylab = "Denisty", main = "Model 22")
lines(density(error_model22), col = "red")
mu_e <- mean(error_model22)
v_e <- var(error_model22)
sd_e <- sqrt(v_e)
x_e <- seq(-10, 16, length = 20)
y_e <- dnorm(x_e, mu_e, sd_e)
lines(x_e, y_e, col = "blue")